// <auto-generated />
using System;
using FullPortManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullPortManagementSystem.Migrations
{
    [DbContext(typeof(PortDbContext))]
    [Migration("20250517075635_AddContainerSubtypeToVesselEvents")]
    partial class AddContainerSubtypeToVesselEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullPortManagementSystem.Models.VesselEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("berth_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("berth_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("eta_hour")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("planned_departure_hour")
                        .HasColumnType("time");

                    b.Property<int>("vessel_size")
                        .HasColumnType("int");

                    b.Property<string>("vessel_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weather_score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VesselEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
